# Generated by Django 2.2.1 on 2019-06-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='store.Cart'),
            preserve_default=False,
        ),
    ]
