# Generated by Django 2.2.1 on 2019-06-26 12:51

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20190626_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=store.models.image_folder),
        ),
    ]
