# Generated by Django 2.2.1 on 2019-06-26 12:52

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190626_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=store.models.image_folder),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=store.models.image_folder),
        ),
    ]
